Feature/multiple projects per single user
openstad/openstad-headless pull request #175
Opened 2024-01-31 10:36 UTC by BartWtje

Functionaliteit voor het koppelen van een enkele gebruiker aan meerdere projecten zal voor nu samengevoegd worden na overleg met Daan en Lorenzo. Deze code werkte in principe foutloos op de frontend- Op de backend gaat dit nog verkeerd omdat een nieuw aangemaakt project nog niet van zichzelf authenticatie waarden toegewezen krijgt bij het aanmaken hiervan. Op dit moment werkt het dus alleen nog niet met nieuw aangemaakte projecten. Dit zal in een ticket gezet worden wanneer deze branch goedgekeurd is.

(Er zullen wel eerst nog wat kleine tests/bug fixes gedaan worden om te checken of alles nog werkt voordat ik reviewers toewijs.)

2024-02-01 09:53 UTC, LorenzoJokhan commented on apps/admin-server/src/components/dialog-user-create.tsx
> +      setOpen(false);
Ik zou dit in een finally block zetten, wat als de createUser zou falen?

2024-02-01 09:55 UTC, LorenzoJokhan commented on apps/admin-server/src/hooks/use-users.tsx
> -    postcode?: string
Al deze velden zijn niet meer van toepassing bij het aanmaken van een gebruiker?

2024-02-01 09:57 UTC, LorenzoJokhan requested changes
1, mogelijk twee changes.

2024-02-16 09:25 UTC, LorenzoJokhan commented on apps/admin-server/src/components/dialog-user-create.tsx
> +      setOpen(false);
Dus de setOpen(false) in de finally

2024-05-27 10:11 UTC, nlsvgtr commented
Dit is achterhaald: er is inmiddels een andere oplossing geimplementeerd.

2024-05-27 10:11 UTC, closed without merging