Feature/form generator v1
openstad/openstad-headless pull request #198
Opened 2024-02-08 09:32 UTC by iandebruin98

2024-02-08 12:12 UTC, rudivanhierden requested changes

2024-02-09 08:16 UTC, LorenzoJokhan commented on packages/ui/src/form-elements/map/index.tsx
> +    // TODO: Get map value when setting a marker. The function to retrieve the value is not yet implemented
De Editormap zit nu in de main. Heeft dit component de handler waarmee je de value op kan halen? Of moet Niels dit nog aanmaken?

2024-02-09 08:18 UTC, LorenzoJokhan commented on packages/ui/src/form-elements/map/map.css
Denk dat de css classname wellicht iets specifieker moet. Als een andere lib ook de naam ".map-container" gebruikt dan kan dit voor styling issues zorgen

2024-02-09 08:21 UTC, LorenzoJokhan commented on packages/ui/src/form-elements/tickmark-slider/index.tsx
> +            <datalist id="tickmarks">
Wellicht de id tickmarks iets specifieker maken? Als een parent site dezelfde id ergens anders op de pagina gebruikt dan kan dit voor styling issues zorgen

2024-02-09 08:27 UTC, LorenzoJokhan commented on packages/form/src/form.tsx
> +     submitHandler = () => {},
In de oude openstad hadden we bij bijvoorbeeld de resource-form de mogelijkheid om een "opslaan als concept" knop toe te voegen als deze voor het aanmaken van een nieuwe resource gebruikt wordt. 
Kan er worden toegevoegd dat er een array van submittext en handlers kunnen worden opgegeven?

2024-02-09 08:28 UTC, LorenzoJokhan requested changes
Ziet er echt heel mooi uit. Goed getyped ook. Heb nog wel wat kleine opmerkingen hierover

2024-02-12 09:32 UTC, LorenzoJokhan approved these changes

2024-02-13 09:28 UTC, merged