admin updates op basis van interne feedback
openstad/openstad-headless pull request #334
Opened 2024-04-09 13:06 UTC by freekDraad

2024-04-10 12:59 UTC, rudivanhierden requested changes
Ziet er goed uit! Nog wel wat vragen / verbeterpuntjes

2024-04-11 07:17 UTC, freekDraad commented on apps/admin-server/src/pages/projects/[project]/settings/notifications.tsx
> +                      <InfoDialog content={'Dit email adres wordt gebruikt voor: ...'} />
Klopt, hier moet nog content voor bedacht worden

2024-04-11 07:17 UTC, freekDraad commented on apps/admin-server/src/pages/projects/[project]/widgets/begrootmodule/[id]/display.tsx
> +                  <InfoDialog content={'TODO'} />
Ook deze moet nog bedacht worden

2024-04-11 07:19 UTC, freekDraad commented on apps/admin-server/src/pages/projects/[project]/widgets/resourceform/[id]/submit.tsx
> +                  <InfoDialog content={'TODO'} />
Ook deze moet nog bedacht worden

2024-04-11 07:33 UTC, rudivanhierden approved these changes

2024-04-11 07:33 UTC, merged