Bugfix/fix buttons in resource map
openstad/openstad-headless pull request #341
Opened 2024-04-11 12:54 UTC by nlsvgtr

- buttons waren uitgecomment in een build fix; deze variant build wel
- basemap had wel een style optie voor hoogte maar gebruikte die niet

2024-04-15 11:16 UTC, rudivanhierden approved these changes

2024-04-15 11:17 UTC, rudivanhierden commented
Zit nog wel een build error in: 
![image](https://github.com/openstad/openstad-headless/assets/205926/dfcbf18b-e4c7-4187-9876-20c58f0b6755)

2024-04-15 11:18 UTC, rudivanhierden requested changes
Zit nog een build error in: 
![image](https://github.com/openstad/openstad-headless/assets/205926/ca9a81da-f406-49cd-be7d-e1ac99cd9cd2)

2024-04-15 12:50 UTC, nlsvgtr commented
Gefixed door `@types/react` dependencies gelijk te trekken

2024-04-16 12:03 UTC, rudivanhierden approved these changes

2024-04-16 15:06 UTC, merged