Feature/admin project comments settings
openstad/openstad-headless pull request #360
Opened 2024-04-16 14:18 UTC by nlsvgtr

- project.config.comment is uitgebreid met wat missende settings
- de admin is geupdate om die settings mee te kunnen beheren

2024-04-16 15:09 UTC, rudivanhierden requested changes
Ziet er goed uit! Kleine opmerking nog

2024-04-16 15:09 UTC, rudivanhierden commented on apps/admin-server/src/pages/projects/[project]/settings/comments.tsx
> +                          <Input placeholder="typ een tekst" {...field} />
Moet dit niet een number field zijn?

2024-04-16 15:09 UTC, rudivanhierden commented on apps/admin-server/src/pages/projects/[project]/settings/comments.tsx
> +                          <Input placeholder="typ een tekst" {...field} />
Net als deze?

2024-04-16 16:06 UTC, nlsvgtr commented on apps/admin-server/src/pages/projects/[project]/settings/comments.tsx
> +                          <Input placeholder="typ een tekst" {...field} />
Ja, dat is veel mooier

2024-04-16 16:07 UTC, nlsvgtr commented
Ik heb verder sentiment er weeer uitgehaald: ik denk dat dat op widget niveau moet, omdat ik me situaties kan voorstellen waar je verschillende widgets met verschillende settings wilt kunnen gebruiken.

2024-04-17 06:59 UTC, rudivanhierden approved these changes

2024-04-17 07:00 UTC, merged