Fix/enschede 3 9
openstad/openstad-headless pull request #577
Opened 2024-09-03 09:14 UTC by freekDraad

- Interactieve kaart: lange filters overlappen met resources
- Interactieve kaart: max-width van de kaart
- Interactive afbeelding: verschillende afbeelding formaten zorgen voor verschillende zommniveau's
- Kaart van Amsterdam is altijd ff in beeld als de pagina laadt
- Filter knop teksten

2024-09-04 09:48 UTC, iandebruin98 requested changes
Typescript errors oplossen s.v.p. En daarnaast zijn 7.000 wijzigingen net wat aan de vele kant om te reviewen. Hopen voor jou dat je goede code hebt geschreven!

2024-09-04 10:42 UTC, freekDraad commented
> Typescript errors oplossen s.v.p. En daarnaast zijn 7.000 wijzigingen net wat aan de vele kant om te reviewen. Hopen voor jou dat je goede code hebt geschreven!

Eens, al zou je natuurlijk even kunnen filteren op de .tsx bestanden. De rest is allemaal gecompileerd.

2024-09-05 07:24 UTC, iandebruin98 approved these changes

2024-09-05 07:24 UTC, iandebruin98 commented on apps/admin-server/src/pages/projects/[project]/widgets/documentmap/[id]/general.tsx
Waarom haal je deze eigenlijk weg? Overbodig bij deze widget zeker?

2024-09-05 11:03 UTC, freekDraad commented on apps/admin-server/src/pages/projects/[project]/widgets/documentmap/[id]/general.tsx
Klopt, de zoom gaat nu automatisch, omdat niet alle documenten dezelfde afmetingen hebben

2024-09-05 12:20 UTC, merged